layout_spectrum: 0.1255319
color:
  saturation: 0.3202743
  lightness: 0.1918254
  brandStrength: 0.65921
  brandColors:
    - '#7C93C6'
    - '#00549F'
    - '#FFDF6B'
    - '#000000'
    - '#761E13'
  rhythmicContrast: 0.2516834
typography_spectrum: 0.6723405
name: Suburban Fresh Farm
